InforceTask/Models/Url.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InforceTask.Models
{
	public class Url
	{
		[Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

		[Required]
		public string LongUrl { get; set; } = string.Empty;

		public string? ShortUrl { get; set; }

		[MaxLength(50)]
		public string CreatedBy { get; set; } = "Anonymous";

		public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
	}
}

InforceTask/Controllers/UrlController.cs
using InforceTask.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace InforceTask.Controllers
{
	public class UrlController : Controller
	{
		private readonly IUrlRepository _urlRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public UrlController(IUrlRepository urlRepository, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
		{
			_urlRepository = urlRepository ?? throw new ArgumentNullException(nameof(urlRepository));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
        }

		public async Task<ActionResult<IEnumerable<Url>>> ShortUrlsTable()
		{
			var urls = await _urlRepository.GetAllUrlsAsync();
			UrlTableViewModel urlTableViewModel = new UrlTableViewModel { Urls = urls };
			return View(urlTableViewModel);
		}
		public async Task<IActionResult> ShortUrlInfo(int id)
		{
			var url = await _urlRepository.GetUrlByIdAsync(id);
			if (url == null)
			{
				return NotFound();
			}
			return View(url);
		}
		public IActionResult About()
		{
			return View();
		}
		[Authorize]
		public IActionResult Add()
		{
			UrlAddViewModel urlAddViewModel = new UrlAddViewModel();
			return View(urlAddViewModel);
		}
		[HttpPost]
		[Authorize]
		public async Task<IActionResult> Add([FromBody] UrlAddViewModel urlAddViewModel)
		{
			Url urlToAdd = new Url
			{
				LongUrl = urlAddViewModel.LongUrl,
				ShortUrl = _urlRepository.ShortenUrlAlgorithm(urlAddViewModel.LongUrl),
				CreatedBy = _signInManager.IsSignedIn(User) ? _userManager.GetUserName(User) : "Anonymous",
				CreatedDate = DateTime.Now
			};
			var urls = await _urlRepository.GetAllUrlsAsync();
			if (urls.Any(u => u.LongUrl == urlToAdd.LongUrl || u.ShortUrl == urlToAdd.ShortUrl))
			{
				return BadRequest("Duplicate URL");
			}
			await _urlRepository.AddUrlAsync(urlToAdd);
			return Ok(urlToAdd);
		}
		[Authorize]
		public async Task<IActionResult> Delete(int id)
		{
			Url? urlToDelete = await _urlRepository.GetUrlByIdAsync(id);
			if (urlToDelete == null)
			{
				return NotFound("This url does not exist");
			}
			_urlRepository.DeleteUrl(urlToDelete);
			await _urlRepository.SaveChangesAsync();
			return RedirectToAction(nameof(ShortUrlsTable));
		}
		[Route("s/{url}")]
		public async Task<IActionResult> RedirectToOriginalUrl(string? url)
		{
			if (string.IsNullOrEmpty(url))
			{
				return RedirectToAction("Index", "Home");
			}
			string fullUrl = "https://localhost:7074/s/" + url;
			if (url.StartsWith('~') && url.EndsWith('~'))
			{
				var urls = await _urlRepository.GetAllUrlsAsync();
				var foundUrl = urls.FirstOrDefault(u => u.ShortUrl == fullUrl);
				if (foundUrl != null)
				{
					return Redirect(foundUrl.LongUrl);
				}
				return NotFound();
			}
			return Redirect(fullUrl);
		}
		public IActionResult Index()
		{
			return View();
		}
	}
}

InforceTask/Views/Url/About.cshtml
<h5>The algorithm takes everything after the last '/' and removes every second character, then adds a '#' at the start and at the end of the resulting url (to differ it from another url)</h5>
<h5>Just copy the short url from the table and watch it redirect you to the full url!</h5>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Understood</a>

InforceTask/Views/Url/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

InforceTask/Views/Url/ShortUrlInfo.cshtml
@model Url
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<div>
	<h3>Original url: @Model.LongUrl</h3>
	<h3>Shortened url: @Model.ShortUrl</h3>
	<h5>Created by: @Model.CreatedBy</h5>
	<h5>Date of creation: @Model.CreatedDate</h5>
	@if (SignInManager.IsSignedIn(User) && UserManager.GetUserName(User) == Model.CreatedBy)
	{
		<a class="btn btn-danger" asp-controller="Url" asp-action="Delete" asp-route-Id=@Model.Id>Delete this url</a>
	}
</div>

InforceTask/Views/Url/ShortUrlsTable.cshtml
@model UrlTableViewModel
@inject SignInManager<IdentityUser> SignInManager

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>

<div ng-app="urlApp" ng-controller="urlController">
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>

    @if (SignInManager.IsSignedIn(User)){
        <form ng-submit="addUrl()">
            <div>
                <label for="longUrl">Input the url here:</label>
                <input type="text" ng-model="newUrl.longUrl" required />
            </div>
            <button type="submit" class="btn btn-primary">Add Url</button>
        </form>
    }

    <table style="width:90%">
        <tr>
            <th>Long Url</th>
            <th>Short Url</th>
            <th>Actions</th>
        </tr>
        <tr ng-repeat="url in urls">
            <td>{{ url.longUrl }}</td>
            <td>{{ url.shortUrl }}</td>
            <td>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="btn btn-primary" href="/Url/ShortUrlInfo/{{ url.id }}">Details</a>
                }
            </td>
        </tr>
    </table>
</div>

<script>
    var app = angular.module('urlApp', []);

    app.controller('urlController', function($scope, $http) {
        $scope.urls = @Html.Raw(Json.Serialize(Model.Urls));

        $scope.addUrl = function () {
            $http.post('/Url/Add', $scope.newUrl).then(function (response) {
                $scope.urls.push(response.data);
                $scope.newUrl = {};
            }).catch(function (error) {
                if (error.status === 400) {
                    alert("Error: " + error.data);
                } else {
                    console.error("Error adding URL:", error);
                }
            });
        };
    });
</script>